# Generated by Django 5.0.7 on 2024-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images')),
                ('description_title', models.CharField(max_length=200)),
                ('description_base', models.TextField()),
                ('price', models.DecimalField(decimal_places=0.0, max_digits=2)),
                ('discount_price', models.DecimalField(decimal_places=0.0, max_digits=2)),
                ('percent_price', models.IntegerField()),
                ('count_view', models.IntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('ctg', models.ManyToManyField(to='user.category')),
            ],
        ),
    ]
